### ISSUE TITLE
Componente de alerta não preenche todo o espaço na célula

### ISSUE THREAD

**Issue by evertonscoelho** [laboratoriobridge/bold#473]
Assim o mesmo não fica alinhado com os demais componentes.

![image](https://user-images.githubusercontent.com/11758594/65705705-5e4b0300-e05f-11e9-8487-3c5687f1fcdf.png)

**Comment by CarlosBonetti** [comment]
Esse comportamento é esperado no Alerta tipo `inline`. Somente o alerta tipo normal preenche todo o espaço disponível, porém possui padding diferente.

Para manter o Alerta inline, porém preenchendo todo o espaço, pode usar

```
<Alert inline style={{ display: 'block' }}>...</Alert>
```
