### ISSUE TITLE
[Select] MultiSelect throws an exception when onBlur is selected but onFocus isn't

### ISSUE THREAD

**Issue by carvallegro** [laboratoriobridge/bold#535]
### Description
When a MultiSelect has a `onBlur` specified and no `onFocus` it throws an exception when I open the Select and hover one of the items (see below). 

![image](https://user-images.githubusercontent.com/1234061/73799414-093bac80-480a-11ea-8f79-0ae3734f8edc.png)

To fix it I had to add ` onFocus={() => {}}`. 

### To Reproduce
```
<FormControl label='Components' required htmlFor="components">
            <Select
              name='components'
              multiple
              items={Object.values(components)}
              itemToString={R.prop('label')}
              onBlur={() => setFieldTouched('components')}
            />
          </FormControl>
```

### Desired behaviour

I should be able to specify `onBlur` without having to specify `onFocus`

**Comment by CarlosBonetti** [comment]
Hi @carvallegro, thanks for the feedback!

I fixed it at https://github.com/laboratoriobridge/bold/pull/536, it was a very tiny mistake inside the focus handler implementation :man_facepalming: 

It's fixed on master and should be available on the next release, planned to this week. Let me know if you have any other problems.

Thanks!
