### ISSUE TITLE
Componente de competência

### ISSUE THREAD

**Issue by thaisalacerda** [laboratoriobridge/bold#597]
- [x] Novo componente: ["Seletor de competência"](https://www.figma.com/file/ednKInwMQ2VQumVyqgVd1j/Atendimento?node-id=1490%3A425):

-  Ao clicar no botão, deve ser aberto o MonthPicker.
- [Este componente de DatePicker](https://www.figma.com/file/TE9FUDtlgVQ4FWlAPtTagxQU/Bold-Design-System?node-id=0%3A5332) tem um comportamento similar de paginação de competência.
- Componente do Bold: [MonthPicker](https://www.figma.com/file/TE9FUDtlgVQ4FWlAPtTagxQU/Bold-Design-System?node-id=129%3A6808) .

**Comment by laiseing** [comment]
Componentes no storybook:
[Monthpicker](https://bold.bridge.ufsc.br/storybook/?path=/story/components-monthpicker--default)
[Select inline](https://bold.bridge.ufsc.br/storybook/?path=/story/components-selectinline--default)
