### ISSUE TITLE
[Button Group] Rename Button Group to Content Switch

### ISSUE THREAD

**Issue by laiseing** [laboratoriobridge/bold#599]
Rename Button Group to **Content Switch** so it equalizes Figma and Bold website to Storybook.

**Comment by CarlosBonetti** [comment]
The `ButtonGroup` component is actually just a building block for building the content switch. There might exist scenarios where we need a `ButtonGroup` but without the content switching functionality.

So what we could do here is create a `ContentSwitch` component providing this functionality that currently `ButtonGroup` doesn't provide.
