### ISSUE TITLE
[Icon]  Add tooth icon

### ISSUE THREAD

**Issue by zDudaHang** [laboratoriobridge/bold#788]
## Component to amend
Icon

## Visual
![Screenshot from 2023-02-13 11-15-18](https://user-images.githubusercontent.com/25747989/218481807-1a993cd4-aad7-44f8-8023-0e95635622f6.png)

## Context
Adding the new icons to be used ;)

**Comment by alisson-fs** [comment]
The icon's svg file generated by Figma is having trouble importing into Bold.

**Comment by lucasjoao** [comment]
A new issue should be created to get all new icons from Figma.
