### ISSUE TITLE
[Pivot Table] Aggregators

### ISSUE THREAD

**Issue by zDudaHang** [laboratoriobridge/bold#808]
# Aggregators

Aggregators are the options given to the user to calculate the cell value (percentage or count)

### **Visual example**

![Screenshot from 2023-08-09 13-33-08](https://github.com/laboratoriobridge/bold/assets/25747989/6df11fe8-c637-4daa-8cb4-ab811145ff04)

From [figma](https://www.figma.com/file/TE9FUDtlgVQ4FWlAPtTagxQU/Bold-Design-System?type=design&node-id=33103-4697&t=FhcFEp346uCsjuul-0).

**Comment by wagnerbsantos** [comment]
Unassigned myself because the code I had done before is obsolete compared to the current version of the pivot-table
