### ISSUE TITLE
[TOAST] Actionable notification

### ISSUE THREAD

**Issue by juliapedrosaxx** [laboratoriobridge/bold#844]
# Propose a new pattern ✨

A toast is a non-modal dialog that appears and disappears (overlaying) with the purpose of displaying information that requires minimal user interaction. Toasts can close automatically after 5 seconds, or they may require manual close action.

An **actionable notification toast variant** displays non-critical information and allows for interactive elements. It can be highly disruptive, differing from toast default, once the actionable notification is read by screenreader when it appears.

 
### **Visual**
![image](https://github.com/laboratoriobridge/bold/assets/63730484/4ce0554b-bac0-4075-9143-9e3459c303b8)
![image](https://github.com/laboratoriobridge/bold/assets/63730484/9a74504f-0050-4996-9cb2-b0ad3c0515e7)

[Figma prototype.](https://www.figma.com/file/TE9FUDtlgVQ4FWlAPtTagxQU/Bold-Design-System?type=design&node-id=89645-3595&mode=design&t=yzDICXGhswJYxox9-4)

### **Context**
This pattern, which allows for interactive elements, should be used to display non-critical information in the user flow. Avoid using long messages since this component disappears automatically, which could make it difficult for users to read the entire message.

- When using Tab, the focus moves in logical order to buttons or links inside the toast.
- It shouldn't block the user from interacting with the interface. 
- Use the dismiss icon to close flags. The flag must close after an action is taken, or after 5 seconds. If the flag receives hover status, it should be kept open.
- Try to keep the text of the message concise: it can be up to two lines in length. 

### **State**
Badge: True/False

### **Accessibility** 
-  The toast message is read when it appears.
- When using Tab, the focus moves in logical order to buttons or links inside the toast.
- When given focus, space key and enter key activate any buttons inside. The toast can optionally be closed with Escape key.
- If it is possible to close the toast, focus then returns to a logical place in the page.
- The close button is given an ARIA label of aria-label="close", and the icon has aria-hidden="true" so it is ignored by assistive technologies.

**Comment by juliapedrosaxx** [comment]
References: [Magentaa](https://www.magentaa11y.com/checklist-web/toast-snackbar/), [MUI](https://mui.com/material-ui/react-snackbar/) and [Carbon.](https://carbondesignsystem.com/guidelines/content/overview)

**Comment by romulofer** [comment]
# QA
For reference, here is an example of implementation for this component: 


![Image](https://github.com/laboratoriobridge/bold/assets/93731921/15c457ab-f1db-465d-9dd7-31b0bd51f9cb)



![Image](https://github.com/laboratoriobridge/bold/assets/93731921/f8068fe9-4e41-4d2c-8172-68e68702e708)

**Comment by larissadallagnol** [comment]
# QA 

Currently, some component paddings are different from the prototype.

### Title padding ###
How it is: 0px 16px 8px 16px
How it should be: 0px 0px 4px 16px

<details>
<summary>Title image</summary>

![title](https://github.com/laboratoriobridge/bold/assets/110857802/deb67f6b-e318-47c1-b4bc-be72549e3928)



</details>

### Message padding ###
How it is: 0px 16px 8px 16px
How it should be: 0px 0px 8px 16px

<details>
<summary>Message image</summary>

![message](https://github.com/laboratoriobridge/bold/assets/110857802/391540ec-24df-42be-9e92-4f051354fb3a)


</details>
