### ISSUE TITLE
[Tick] The component is receving not recognize props causing a console warning

### ISSUE THREAD

**Issue by GuilhermePrandi** [laboratoriobridge/bold#864]
# Create a bug report to help us improve Bold 💪

Depends on:
- #863 

### **Describe the bug**
The component is having problems with not recognize props, as "vertichalAnchor" and "visibleTickCount"

### **To Reproduce**
1. Using the component Tick calling inside a Chart Component
 
### **Expected behavior**
Do not throw warning console to a not recognize props
 
### **Screenshots**
![Image](https://github.com/user-attachments/assets/5d96295d-adf0-44c6-a1e6-1d689a14bbe4)

**Comment by carolinapsil** [comment]
## Issue
### Console warning
Console warnings are still thrown when using the Range Area and the Composed Chart components.

Range Area:

![Image](https://github.com/user-attachments/assets/e576f117-60bb-4bf2-9e99-170054b781e3)

Composed Chart:
![Image](https://github.com/user-attachments/assets/3f464f4a-8667-49ca-b418-1909c371feee)


- [ ] **Developed**
- [ ] **Tested**
