### ISSUE TITLE
[UseMeasure] Writing tests for useMeasure hook

### ISSUE THREAD

**Issue by GuilhermePrandi** [laboratoriobridge/bold#875]
Depends by #863 

## Component to amend

UseMeasure

## Context

In this [issue](https://github.com/laboratoriobridge/bold/issues/863) a new useMeasure hook has added to the repository, and have the necessity to write tests for this new hook to cover and validate the hook behavior 

[useMeasure](https://github.com/laboratoriobridge/bold/blob/7dc224dfe328ee9890223c280be6a138b69e30e9/src/hooks/useMeasure.ts)

**Comment by wagnerbsantos** [comment]
It was decided to close this issue because this hook was copied/simplified from another repository where it was already tested.
Because it wasn't implemented exacty as the original, I was unable to mock it properly to recreate the tests.
